# Generated by Django 2.2.6 on 2020-03-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_auto_20200315_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpublisher',
            name='publisheraddress',
        ),
    ]
